site_name: RTK文档网站
site_url: https://mydomain.org/mysite
nav:
  - 主页: index.md
  - 通用注意事项: general/general.md
  - 板卡手册:
    - 集成4G系列:
      - B94: b94/b94.md
      - B84: b84/b84.md
      - B74: b74/b74.md
    - 集成WIFI系列:
      - W80: w80/w80.md 
    - 集成数传系列:
      - B92: b92/b92.md
      - B80: b80/b80.md
      - B72: b72/b72.md
    - 仅RTK系列:
      - B50: b50/b50.md
      - R50/R20: r50/r50.md
  - 无人机使用:
    - 支持的飞控: fmu/fmu.md
    - 地面站设置:
      - Mission Planner: mp/mp.md
      - QGC: qgc/qgc.md
    - 定向改配置: heading/heading.md
  - ROS2使用: ros2/ros2.md
  - RTK学习: 
    - RTK原理: rtk/rtk.md
    - 单北斗模式: rtk/BDonly.md
  - 其它资料: other/other.md
theme:
  name: material
  language: zh
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg 
extra_css:
  - stylesheets/extra.css
