site_name: RTK文档网站
site_url: https://mydomain.org/mysite
nav:
  - 主页: index.md
  - 通用注意事项: general.md
  - 板卡手册:
    - 4G系列:
      - B94: b94.md
      - B84: b84.md
      - B74: b74.md
    - 自带数传系列:
      - B92: b92.md
      - B80: b80.md
      - B72: b72.md
    - 其他:
      - B50: b50.md
      - R50: r50.md
      - R20: r20.md
  - 地面站设置:
    - Mission Planner: mp.md
    - QGC: qgc.md
  - ROS2使用: ros2.md
  - 其它资料: other.md
  - RTK学习: rtk.md
theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_css:
  - stylesheets/extra.css